# Configuration for Compose https://detekt.dev/compose.html#configurations-3

config:
  warningsAsErrors: true

complexity:
  LongMethod:
    threshold: 100 # Composable functions with lists can't be small
  LongParameterList:
    ignoreDefaultParameters: true # it seems ok to have many parameters in Composables

formatting:
  MaximumLineLength:
    active: false # Duplicates MaxLineLength rule
  NoWildcardImports:
    active: false # Duplicates WildcardImport rule

style:
  UnusedPrivateMember:
    active: false # because of Composable Previews
  MagicNumber:
    active: false # because of Colors
  WildcardImport:
    active: false # Clashes with default IntelliJ behavior

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
