# Configuration for Compose https://detekt.dev/compose.html#configurations-3

config:
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true # it seems ok to have many parameters in Composables

style:
  UnusedPrivateMember:
    active: false # because of Composable Previews
  MagicNumber:
    active: false # because of Colors

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
